laserscan_multi_merger:
  ros__parameters:
    destination_frame: "base_link"
    cloud_destination_topic: "/merged_cloud"
    scan_destination_topic: "/merged_scan"
    laserscan_topics: "/rplidar/filtered_scan /velodyne/filtered_scan"
    angle_min: -180.0
    angle_max: 180.0
    angle_increment: 0.00437
    scan_time: 0.0
    range_min: 0.2
    range_max: 25.0

