laserscan_multi_merger:
  ros__parameters:
    destination_frame: "merge_laser"
    scan_destination_topic: "/merged_scan"
    laserscan_topics: "/rplidar/filtered_scan /velodyne/filtered_scan"
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.0058
    scan_time: 0.05
    range_min: 0.2
    range_max: 25.0

